{{- if include "maia.createApiKeySecret" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "maia.fullname" . }}-api-key
  labels:
    {{- include "maia.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.maia.security.existingSecretKey }}: {{ .Values.maia.security.apiKey | b64enc | quote }}
{{- end }}
---
{{- if include "maia.createOpenaiSecret" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "maia.fullname" . }}-openai
  labels:
    {{- include "maia.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.maia.embedding.openai.existingSecretKey }}: {{ .Values.maia.embedding.openai.apiKey | b64enc | quote }}
{{- end }}
