apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: maia-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: maia-operator-role
subjects:
- kind: ServiceAccount
  name: maia-operator
  namespace: maia-system
