apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: maia

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - serviceaccount.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - servicemonitor.yaml

commonLabels:
  app.kubernetes.io/part-of: maia
  app.kubernetes.io/managed-by: kustomize

images:
  - name: ghcr.io/ar4mirez/maia
    newTag: latest
