apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: maia-system

resources:
- namespace.yaml
- deployment.yaml

images:
- name: ghcr.io/ar4mirez/maia-operator
  newTag: v0.1.0
